#theme: minima
#title: CS 499 Capstone ePortfolio
#author: Erin Zamora
#description: This artifact is an Inventory App that I truly believe I can enhance it to be even better than it is. It meets all three categories; Software Engineering and Design, Algorithms and Data Structures, and Databases. Enhancing this project will truly show my flexibility as a Computer Scientist.
theme: jekyll-theme-cayman
title: CS 499 Capstone ePortfolio
description: Erin Zamora's Computer Science Portfolio
